apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: agentsmith

bases:
  - ../../base

resources:
  - ingress.yaml

patches:
  - path: patch-dispatcher-prod.yaml
    target:
      kind: Deployment
      name: agentsmith-dispatcher
