apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: agentsmith

resources:
  - namespace.yaml
  - redis/deployment.yaml
  - redis/service.yaml
  - dispatcher/deployment.yaml
  - dispatcher/service.yaml
  - rbac/serviceaccount.yaml
  - rbac/role.yaml
  - rbac/rolebinding.yaml
  - configmap/agentsmith-config.yaml
